### ISSUE TITLE
Time zones?

### ISSUE THREAD

**Issue by alexlinno** [niklaswall/node-red-contrib-light-scheduler#11]
Hi
Is the time always GMT? Or is the global position used for that? It seems always GMT for me

**Comment by niklaswall** [comment]
No, time SHOULD be you configured server time. Are you experiencing any problems that indicate that it does not follow your local time?

Best regards,
Niklas

**Comment by alexlinno** [comment]
Sorry my bad..hadn't set the correct time zone...duhhh
BR
Alex

**Comment by niklaswall** [comment]
Great, that means there is no problem with the code :-)
