### ISSUE TITLE
Node-Red Crashes

### ISSUE THREAD

**Issue by larrybell** [niklaswall/node-red-contrib-light-scheduler#15]
Any idea why this happens? I fixed it by disabling the flow that contained the light scheduler.

[INFO] Disabling SSL
[INFO] Updating IDE Users
[INFO] Adding IDE User admin
[INFO] Updating HTTP Node User
[INFO] Adding HTTP Node User admin
[INFO] Disabling Projects
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v10.0.0
npm info lifecycle node-red-docker@1.0.0~prestart: node-red-docker@1.0.0
npm info lifecycle node-red-docker@1.0.0~start: node-red-docker@1.0.0
> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"
17 May 12:06:14 - [info] 
Welcome to Node-RED
===================
17 May 12:06:14 - [info] Node-RED version: v0.18.5
17 May 12:06:14 - [info] Node.js  version: v10.0.0
17 May 12:06:14 - [info] Linux 4.4.50 arm LE
17 May 12:06:15 - [info] Loading palette nodes
17 May 12:06:23 - [info] Dashboard version 2.9.3 started at /ui
17 May 12:06:25 - [info] Settings file  : /share/node-red/settings.js
17 May 12:06:25 - [info] User directory : /share/node-red
17 May 12:06:25 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
17 May 12:06:25 - [info] Flows file     : /share/node-red/flows.json
17 May 12:06:25 - [warn] 
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
17 May 12:06:25 - [info] Starting flows
17 May 12:06:25 - [info] [inject:d5c1650c.4188b8] repeat = 5000
17 May 12:06:25 - [info] [inject:601383c3.e3d7ec] repeat = 10000
17 May 12:06:25 - [info] Started flows
17 May 12:06:25 - [info] Server now running at http://127.0.0.1:1880/
17 May 12:06:25 - [info] [mqtt-broker:HA-MQTT] Connected to broker: mqtt://172.16.30.127:1883
17 May 12:06:25 - [info] [mqtt-broker:HA-MQTT] Connected to broker: mqtt://172.16.30.127:1883
17 May 12:06:26 - [red] Uncaught Exception:
17 May 12:06:26 - TypeError: Cannot read property 'toFixed' of null
    at setState (/share/node-red/node_modules/node-red-contrib-light-scheduler/light-scheduler.js:39:63)
    at Timeout.evaluate [as _onTimeout] (/share/node-red/node_modules/node-red-contrib-light-scheduler/light-scheduler.js:77:16)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
npm info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-17T17_06_26_740Z-debug.log

**Comment by niklaswall** [comment]
This *should* now be solved. I was not able to reproduce the error but i realized what was causing it, and have fixed the underlying problem that is triggered when no longitude / latitude or settings are available to the node.
