### ISSUE TITLE
What about different dusk/dawn thresholds?

### ISSUE THREAD

**Issue by Dwarfex** [niklaswall/node-red-contrib-light-scheduler#19]
What about different dusk/dawn thresholds? 

You could add different thresholds for dusk and dawn to compensate for rooms having early or late sun.

So you could compensate a room which is dark in the morning but lit by the sun in the evening.

**Comment by niklaswall** [comment]
The current dusk / dawn threshold setting solves this by adjusting for when to "consider it dark".

Increasing to a positive elevation will cause the node to think it gets dark earlier and bright later, while a negative offset will cause the node to think it get's dark later and bright earlier in the morning.

If you wan't different settings per room you currently need to have different Light Schedule nodes for each situation.
