### ISSUE TITLE
Really love light-scheduler but wondering if there is any developing still?

### ISSUE THREAD

**Issue by rhoddan** [niklaswall/node-red-contrib-light-scheduler#23]
Hi Niklas! I think your light scheduler is awesome but unfortunately there are some bugs (especially the #21 gives a lot of problems.

I just wondering if you plan for any updates in near time?

Thanks again for a very useful function!

//Peter from Sweden

**Comment by Onixarts** [comment]
I guess not ;)

**Comment by niklaswall** [comment]
Hi,

Sorry for the lack of attention. For some reason I have not received any notification emails for new posts. I have looked over my email settings, so this should hopefully be resolved now.

I will start looking at reported problems / requests to see what I can resolve!

Thanks for using Light Scheduler! :-)

/Niklas
