### ISSUE TITLE
No output produced

### ISSUE THREAD

**Issue by bakman2** [niklaswall/node-red-contrib-light-scheduler#28]
I moved from a raspberry pi to docker/nas and found this morning that my water heater didn't turn on during the night.

I found that there is no output coming from the node, except when I use the 'minutely' setting. How can i troubleshoot ?

**Comment by niklaswall** [comment]
This is most likely due to wrong timezone or clock settings on your new installation. My best guess is that your docker instance of node-red have the wrong timezone setting or clock and that this is causing the issue.

This thread might help you: https://github.com/node-red/node-red-docker/issues/48

I will try to make it easier to spot these configuration errors since it's a common problem. Especially when running node-red in docker.
 
/Niklas

**Comment by bakman2** [comment]
The timezone is correct;

```
NAS:/volume1/docker/nodered/data# date
Wed Apr 24 14:20:13 CEST 2019
NAS:/volume1/docker/nodered/data# docker exec -it nodered sh
$ date
Wed Apr 24 14:20:31 CEST 2019
```

Formatted timestamp is also correct:

![Screenshot 2019-04-24 at 14 27 27](https://user-images.githubusercontent.com/333960/56659349-28af8180-669d-11e9-9362-f792b04ac079.jpg)

**Comment by bakman2** [comment]
And note that I do see the node status changing from ON to OFF and vice versa, but no payload is sent.

**Comment by niklaswall** [comment]
Ok, so I suspect that this is related to a recent fix that should prevent output when nothing has changed... however it does work for me running node-red version 0.20.5.

What version of node-red and nodejs are you running?

**Comment by bakman2** [comment]
I moved back to a raspberry pi, clean install, same issue.

```
Node-RED version: v0.20.5
Node.js  version: v10.15.3
Linux 4.14.98-v7+ arm LE
NPM 6.9.0
```

**Comment by niklaswall** [comment]
Ok, thank you for the information. 
Can you select the Light Schedule node and go to the top-left menu in node-red and select Export -> clipboard, Select "selected nodes" and post that JSON blob?

I will do a clean install on a Raspberry Pi and try to reproduce your setup, because something strange is going on. I currently have it running on two instances of node-red and it works fine for me.

**Comment by bakman2** [comment]
Yes it is kind of weird that it doesn't produce output.

```
[{"id":"93dc8f77.d4e978","type":"light-scheduler","z":"4e0a25b.1d423dc","settings":"be61ed6a.5a89c","events":"[{\"start\":{\"dow\":4,\"mod\":645},\"end\":{\"dow\":4,\"mod\":1200}},{\"start\":{\"dow\":5,\"mod\":675},\"end\":{\"dow\":5,\"mod\":1020}}]","topic":"test","name":"","onPayload":"ON","onPayloadType":"str","offPayload":"OFF","offPayloadType":"str","onlyWhenDark":false,"scheduleRndMax":0,"sunElevationThreshold":6,"sunShowElevationInStatus":false,"outputfreq":"output.statechange.startup","x":322,"y":330,"wires":[["f48fd0ad.feffb8"]]},{"id":"f48fd0ad.feffb8","type":"debug","z":"4e0a25b.1d423dc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":490,"y":330,"wires":[]},{"id":"be61ed6a.5a89c","type":"light-scheduler-settings","z":"","name":"my settings","latitude":"52.1","longitude":"4.4"}]
```

**Comment by niklaswall** [comment]
I have now tested with your exact configuration and versions of NodeJS and Node-RED and it works for me. Have you checked what version of the node you are running?

Go to menu -> Manage Palette and search for the node. You want the latest 0.0.12 version that was published.

**Comment by bakman2** [comment]
node-red-contrib-light-scheduler
0.0.12

**Comment by niklaswall** [comment]
:-( I'm starting to run out of ideas.
Do you get any errors in the console?
Is everything else working fine on your node-red installation?

If you set the node to minutely and put an RBE node directly after, that should solve you problem.... but it should not be needed.

**Comment by bakman2** [comment]
I suspect it is caused by the missing `{` `}` `;` in the `if` statements (bad practice to leave the semicolons out) it is currently fully depended on proper idents.

**Comment by niklaswall** [comment]
The code follows the defined linting definition, and i have double-checked all if statesmen and couldn't find anything faulty.... with that said, i could definitely have missed something, so please point me to the line you think is faulty and i will check it.

I suspect that it's the call to RED.util.compareObjects that is causing the issue (and that is also relatively newly added)... Will try to change that to something more fail-safe and see if that solves the problem.

**Comment by niklaswall** [comment]
I fixed a minor bug that could have caused this issue for you in version 0.0.13 release just now.

Please verify if that solved the problem for you!

Best regards,
Niklas

**Comment by bakman2** [comment]
@niklaswall would you look at this 🤠

![Screenshot 2019-04-30 at 15 31 27](https://user-images.githubusercontent.com/333960/56965269-26e23400-6b5d-11e9-82d3-31fae60ee5d1.jpg)

Thanks so much for you support!

**Comment by niklaswall** [comment]
Amazing! :-)

I'm glad that it works again.

/Niklas
