### ISSUE TITLE
Offset for ”dark” calculation

### ISSUE THREAD

**Issue by rhoddan** [niklaswall/node-red-contrib-light-scheduler#3]
Thanks for a great node!
Is it possible to add a offset function for ”only when ”dark”?
Set +60 or -60 means after or before dark

**Comment by niklaswall** [comment]
Absolutely, offset is planned... but i'm a little bit uncertain if offset in minutes is the best way to go. I actually think that it's better to set the sun altitude in relation to the horizon instead (since that would probably mean that you get a better result over the whole year)
