### ISSUE TITLE
problem with v 0.0.14

### ISSUE THREAD

**Issue by rhoddan** [niklaswall/node-red-contrib-light-scheduler#32]
Hi, I have got a strange problem. It's not switched to ON even that everything is matched (correct positition etc)
![Annotation 2019-05-10 110003](https://user-images.githubusercontent.com/33499995/57515499-17a87680-7313-11e9-8076-3353b76a8d0e.jpg)

**Comment by rhoddan** [comment]
Suddenly it seems to work again...

**Comment by footy42** [comment]
any idea what fixed it for you? I'm having the same issue.
I can force it on through overrides, but nothing else seems to work.
