### ISSUE TITLE
Schedule carrying over to next day turns off then on

### ISSUE THREAD

**Issue by chenchen119** [niklaswall/node-red-contrib-light-scheduler#33]
Hi, first of all, thanks for the great project!

I have light schedule everyday from 17:00 to 1:00 with 5 min randomness.
But this will cause a turn off and then on at 0:00 (2 min here):

![image](https://user-images.githubusercontent.com/4780124/58209767-9058ec80-7c9c-11e9-9c82-d0b870582f36.png)

Is there anyway to avoid this from happening?

Thanks

**Comment by niklaswall** [comment]
This is a corner-case that I have missed. Should not be that much work to fix!

**Comment by niklaswall** [comment]
Fix published in v0.0.15!

/Niklas
