### ISSUE TITLE
Suggestion: Multiple outputs

### ISSUE THREAD

**Issue by cybix32** [niklaswall/node-red-contrib-light-scheduler#35]
This is a nice node!

I would like to have multiple outputs, similar to Bigtimer. That would mean that I could wire both "when state changes" and "minutes" from the same node in the same flow.

For example, the same node/schedule will control the reliable z-way-light and the unreliable 433MHz-light (that needs every minute).

And outputstring for logging are also nice.

**Comment by niklaswall** [comment]
The easiest way for you to accomplish this is to configure the node to output on a minutely basis and redirect the output to both your 433Mhz transmitter and a "rbe node" that only forward messages when they have changed.

<img width="667" alt="Screenshot 2020-07-15 at 12 21 20" src="https://user-images.githubusercontent.com/14335133/87534036-cd98ee80-c695-11ea-804f-99588590f8d8.png">
