### ISSUE TITLE
Opposing dusk/dawn thresholds to increase time considered "dark"

### ISSUE THREAD

**Issue by voydz** [niklaswall/node-red-contrib-light-scheduler#37]
Hi there,

first things first: thank you for your awesome work. Absolutely loving your scheduler node and I am using it for over 10 months in my home automation now.

This ticket is a feature request and refers somewhat to #19. It makes total sense, to "move" the timespan, but I often find myself in situations, when I need it to "consider it dark earlier in the evening AND later in the morning". I also get it, that I can use two schedulers for that. But with increasing lights/rooms it gets quite confusing, fast.

So maybe you can give this a thought again?

best regards

**Comment by niklaswall** [comment]
First off, thank you for the praise!

Maybe i misunderstand you, but increasing the "Threshold" to higher sun elevation should make it "consider it dark earlier in the evenings" and "dark later in the morning" which should solve your problem.

The main reason why I made it possible to set the threshold angel instead of a offset-time is to make it more consistent over the year. Since the sun set and rises at different "speed" over the year.

**Comment by voydz** [comment]
Hey,

I am not quite sure how to describe it properly so I made a quick sketch on a sun elevation/time graph.

![](https://i.imgur.com/9s5ZrTN.jpg)

The cyan line shows the current implementation of "moving" by a degree of sun elevation. Effectively maintaining the same timespan throughout the day, where the node considers it a "not dark" state.

My problem is described by the purple line. Which would - as said above - extend the timespan to be considered dark later in the morning and earlier in the evening. I hope it is better to understand that way. 

greetings

**Comment by niklaswall** [comment]
I'm still not sure I follow, both the cyan and purple arrows move in the same direction.... a positive threshold will result in "the horizon moving up" in your graph. If you set the threshold to +10 degrees that will "simulate" that the sun need to pass the +10 horizontal line in your graph, which "moves" the sunset from 03:30 to ~04:50 and the sunset from 19:00 to ~17:60. It will not maintain the same timespan during the day as you write.

![sun-elevation-thresholds2](https://user-images.githubusercontent.com/14335133/79793624-2c79f080-8351-11ea-9ac0-44bcbd3d02d8.jpg)

You have to excuse my bad gimp skills, did not have a good software for sketching installed.

**Comment by niklaswall** [comment]
![sun-elevation-thresholds3](https://user-images.githubusercontent.com/14335133/79825273-e5afe900-8398-11ea-9eee-6cd097dbf706.jpg)

**Comment by voydz** [comment]
/tldr I am closing this, as the suggested behavior is already implemented.

Well, thank you very much for your effort. Your gimp skills are fine. :D 

I have to apologize, the last graph shows exactly which behavior I desired. I guess I failed in observing this due to other factors (different speeds of sun rising/setting as you mentioned). I am sorry for wasting your time.

have a great day

**Comment by niklaswall** [comment]
No, problem. The information might help someone else as well!

//Niklas
