### ISSUE TITLE
switch off minutly output

### ISSUE THREAD

**Issue by TheHackbraten** [niklaswall/node-red-contrib-light-scheduler#41]
Hey there,
i want to use your light scheduler with the output only when state changes option. 
But i sadly had to notice that it only works at the off state. 
At On state i can track a minutly output in the debug window.
Is this a common problem or is there a way to fix this?
If you need, i can post my setup of the scheduler.

**Comment by niklaswall** [comment]
The "Output" setting controls this behavior. 
<img width="348" alt="Output Control" src="https://user-images.githubusercontent.com/14335133/87533316-b7d6f980-c694-11ea-8a92-41056f90f69f.png">

Please let me know if it still don't work for you!
