### ISSUE TITLE
Expected behavior schedule versus sunrise/sunset?

### ISSUE THREAD

**Issue by Erik-NA** [niklaswall/node-red-contrib-light-scheduler#42]
If I configure a schedule to turn on from 06:00 to 23:00 with the settings "auto", "When state change", "Only when dark" and offset 0, whats is the expected behavior when calculated sunrise is 08:45 and calculated sunset is 14:53?

My expectation is that On payload is triggered at 06:00, Off payload at 08:45, On payload at 14:53 and Off payload at 23:00? Is my assumption correct?

**Comment by niklaswall** [comment]
You are correct, the ON payload should be sent at 06:00 and later OFF at 08:45. It will later turn on at 14:53 and be ON until your schedule turns it off at 23:00.

Other "event-based" timers and dusk/dawn solutions fail to handle this correctly which was the main reason why I started to write this plugin.

If it does not work as you write you probably have the wrong time/time-zone configured or the wrong location.
