### ISSUE TITLE
Dusk/Dawn vs Schedule, plus randomness

### ISSUE THREAD

**Issue by balthisar** [niklaswall/node-red-contrib-light-scheduler#48]
A couple of questions, perhaps can be clarified in the documentation, which I'm willing to do when clarified!

- If I _only_ care about dusk/dawn (e.g., exterior lighting), do I have to do anything other than select "only when dark"? 

- Or is this **and**, meaning "when scheduled" **and** "only when dark"? If I schedule all 24 hours, then I would get ON once dark, and OFF once light, correct? (subject to sun elevation, etc.)

- If I have randomness in the above scenario, does it still apply to the ON and OFF times, or only the programmed start and stop times? For example, if I program start at 00:01 and end at 23:59, what is random? The ON and OFF, or the 00:01 and 23:59?

Thanks!

**Comment by niklaswall** [comment]
Hi,

Will try to shine some light on your questions.

The schedule sets "on time" and the setting "only when dark" forces it "off" when the sun is up. So it's "_on if schedule matches **and** only if it's dark_".

The randomness basically only apply to the schedule and then the sun elevation is added on top of that equation. Maybe this is not exactly what one would expect but my thinking is that the sunrise and sunset changes from day to day anyway. So, using random and having a schedule from 00:01 to 23:59 is not going to work well.

I hope I made some sense :-)

**Comment by balthisar** [comment]
Great! Thanks!
