### ISSUE TITLE
Time Zone Selection

### ISSUE THREAD

**Issue by kdubovenko** [niklaswall/node-red-contrib-light-scheduler#5]
Thank you for taking the time to create this useful node. It looks like you are using UTC time for scheduling. I think it would be quite helpful to have a local time offset selector so that the scheduling time would match the actual local time.

**Comment by mars1401** [comment]
Hello, Thank you for this node, it's excatly what I was looking for.
I do have the same issue than kdubovenk, I leave in france and has you can see in the attached file, i have one hour difference(in winter ) with GMT time. 
in addition we have summer/winter  time change, it would be really nice if it could be included as well.
![node red](https://user-images.githubusercontent.com/33986411/33232929-e2e7082c-d20e-11e7-9e2d-4a27dbe96caf.PNG)

**Comment by niklaswall** [comment]
The node should use the server time-zone and what you configure as a schedule should also be time-zone neutral.

@kdubovenko what time-zone are you using?

@mars1401 It looks like only a part of your screenshot was captured, but I will look into this!

**Comment by niklaswall** [comment]
Please verify if this is still a problem with the latest published version!

**Comment by mars1401** [comment]
Thansk a lot, it works now! , I just had to delete the created nodes and create  new ones, as it kept showing an error (missing setting), thanks a lot for your work.
Just for your information I use it, not for light scheduling, but for HVAC control, 
. The idea is to have in every location of my house a wemos d1mini, with a dallas temp probe together with a mini PIR sensor, connected to a raspberry pi3 hosted mqtt broker. 
The scheduler determine what are the usual time i need temperature control (i.e. when my kids are in their bedrooms), but when the PIR sensor will detect somebody, i will overide the scheduler.

**Comment by niklaswall** [comment]
Great!  :+1: 
Perfect that there are other use-cases than controlling light :-)
