### ISSUE TITLE
Can't add a schedule

### ISSUE THREAD

**Issue by Balestrino** [niklaswall/node-red-contrib-light-scheduler#51]
VM908:7 Uncaught TypeError: Cannot read property 'event' of undefined

everytime im trying to add a schedule

**Comment by niklaswall** [comment]
That's strange.

What version of NodeJS and Node-Red are you running?

**Comment by Balestrino** [comment]
node version 10.21.0
node-red version v1.1.0
using docker and i've tried different browsers

**Comment by niklaswall** [comment]
I might have misunderstood the problem. So you get the error in the browser?

**Comment by Balestrino** [comment]
yes the error is by the browser
![gX3TAQq6T](https://user-images.githubusercontent.com/845352/86527103-e76b5200-be9b-11ea-9364-bba236cefaad.png)

**Comment by mickym2** [comment]
In parallel it seems that it has to do with the upgrade to NodeRED v 1.1.x - I opened the issue in parallel. The errors are similar: 
I am not the developer of these nodes: I got the following errors - but I am not sure if they are related to this issue (using Chrome):

vendor.js:4 JQMIGRATE: Migrate is installed, version 3.3.0
red.min.js:16 Node-RED: 1.1.0
red.min.js:16 Versions
red.min.js:16 jQuery 3.5.1
red.min.js:16 jQuery UI 1.12.1
red.min.js:16 ACE 1.4.3
red.min.js:16 D3 3.0.3
DevTools failed to load SourceMap: Could not load content for http://server.fritz.box:1880/vendor/purify.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
2
DevTools failed to load SourceMap: Could not load content for http://server.fritz.box:1880/gridstack.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by niklaswall** [comment]
Have you tried to update to the latest version (0.0.16) of node-red-contrib-light-scheduler?
