### ISSUE TITLE
ON Payload Not Triggered

### ISSUE THREAD

**Issue by statecowboy** [niklaswall/node-red-contrib-light-scheduler#53]
UPDATE - Sorry, I figured out what I was doing wrong.  Didn't realize you have to put a schedule in even if you select the sun angle option.  I ended up filling up the entire schedule and this seemed to fix the issue. 

ISSUE - node does not switch to ON payload state when sun is at or below threshold.  I want to use this to turn on some mqtt lights outside.  

This is my first time using this node, so it's entirely possible that I've done something wrong, although I believe everything is configured correctly.  My MQTT server connection is good and I have configured my location correctly (the sun angle feedback seems to be correct below the node).  However, the node will not switch states to "ON".

I've pasted my flow info below.

`[{"id":"73f5f767.dad938","type":"tab","label":"lightsOutside","disabled":false,"info":""},{"id":"365bc7cb.7d12e8","type":"light-scheduler","z":"73f5f767.dad938","settings":"5b73ffcf.5c1d9","events":"[]","topic":"","name":"Turn Off Outside Lights At Night","onPayload":"on","onPayloadType":"str","offPayload":"off","offPayloadType":"str","onlyWhenDark":true,"scheduleRndMax":0,"sunElevationThreshold":"6","sunShowElevationInStatus":true,"outputfreq":"output.statechange.startup","x":150,"y":360,"wires":[["bd3d1ba9.a413b8","a3f2af9c.adc89","36e73104.bffa6e"]]},{"id":"bd3d1ba9.a413b8","type":"mqtt out","z":"73f5f767.dad938","name":"Patio Light","topic":"cmnd/patio/POWER","qos":"2","retain":"","broker":"a7903fbb.08a58","x":430,"y":300,"wires":[]},{"id":"a3f2af9c.adc89","type":"mqtt out","z":"73f5f767.dad938","name":"Front Porch Light","topic":"cmnd/frontporch/POWER","qos":"2","retain":"","broker":"a7903fbb.08a58","x":450,"y":360,"wires":[]},{"id":"36e73104.bffa6e","type":"mqtt out","z":"73f5f767.dad938","name":"Garage Light","topic":"cmnd/garage/POWER","qos":"2","retain":"","broker":"a7903fbb.08a58","x":430,"y":420,"wires":[]},{"id":"5b73ffcf.5c1d9","type":"light-scheduler-settings","z":"","name":"Kansas City","latitude":"39.0570111","longitude":"-94.57455277777777"},{"id":"a7903fbb.08a58","type":"mqtt-broker","z":"","name":"","broker":"192.168.1.246","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]`

**Comment by niklaswall** [comment]
Yes, you are right. It's the combination of the schedule and the dusk/dawn settings that normally activates the output.

//Niklas
