### ISSUE TITLE
JS Error when creating schedule

### ISSUE THREAD

**Issue by tfoote000** [niklaswall/node-red-contrib-light-scheduler#55]
Hello, I am getting an error when I try to edit any of my light scheduler nodes. I have refreshed my cache and cookies and that doesn't help. It seems to have happened right once I updated to Node-Red 1.1.0. I am running NodeRed in Docker.

Here is a screen shot of the error
![Screen Shot](https://user-images.githubusercontent.com/38013852/87253201-78ab6d00-c436-11ea-8a07-4c1c6f8661f2.png)

**Comment by xbonnaire** [comment]
Hi. You can see issue #52 (https://github.com/niklaswall/node-red-contrib-light-scheduler/issues/52) which solves this problem. You have to update your version of the light scheduler to 0.0.16.

**Comment by niklaswall** [comment]
Please let me know if this still does not work after the 0.0.16 update!

//Niklas
