### ISSUE TITLE
auto - mode not working

### ISSUE THREAD

**Issue by mzsolnay** [niklaswall/node-red-contrib-light-scheduler#56]
Hi !

Great node, I was very happy to find it. I would like to use it to switch ON/OFF the pump in my garden pond.

English is not my native language, maybe I do not use the node correct, but it is not working.

See screenshot from my test flow and node settings
![scheduler1](https://user-images.githubusercontent.com/7197310/87520811-c36df480-c683-11ea-91a7-2f971f543410.JPG)
![scheduler2](https://user-images.githubusercontent.com/7197310/87520832-cb2d9900-c683-11ea-86a1-42cd061e004b.JPG)

Manual ON/OFF is working fine. AUTO turns the ovveride off, but output stays OFF, regardless, the setting, that it should be ON this time of day...

Don't know, what I'am missing ... butu as said, not native english and also being quiet a newbie with node-red

**Comment by niklaswall** [comment]
You probably want to change the "Dusk / Dawn" setting to "Schedule Only" to make it ignore the sun elevation and only use the schedule.

**Comment by mzsolnay** [comment]
PERFECT, that was the key ! Thank you very much for the quick response, for the help, and for the great node !!!

**Comment by niklaswall** [comment]
No problem!

//Niklas
