### ISSUE TITLE
State is getting outputted every minute, then output is set to when state changes

### ISSUE THREAD

**Issue by timkoers** [niklaswall/node-red-contrib-light-scheduler#59]
I am using this node in the middle of a flow with two nodes connected to the light scheduler's input.

When the current season changes to winter,  the light scheduler get's an msg.payload = stop message. This did not occur yet, obviously.

When the season is anything other than winter, the light scheduler get's an msg.payload=schedule-only. This message is being send on season change.
The light scheduler is outputting according to it's schedule, but the light scheduler is outputting that message every minute, despite the Output -> `when state changes` flag being set. There was no override enabled.
I think the problem lies [here](https://github.com/niklaswall/node-red-contrib-light-scheduler/blob/master/light-scheduler.js#L22)  and [here](https://github.com/niklaswall/node-red-contrib-light-scheduler/blob/master/light-scheduler.html#L57) 

Please keep in mind, I am using the `when state changes` option, not the `when state changes + startup` option 
EDIT: It is also happening whilest the output is set to `when state changes + startup`

**Comment by niklaswall** [comment]
Hi timkoers,

can you provide a sample flow to demonstrate this behavior?

I'm currently not able to reproduce this behavior.

//Niklas

**Comment by timkoers** [comment]
Sure, here is the JSON

`[
    {
        "id": "81b7e62e.27b9a8",
        "type": "tab",
        "label": "Appliances",
        "disabled": false,
        "info": ""
    },
    {
        "id": "ed62fb74.b88888",
        "type": "light-scheduler",
        "z": "81b7e62e.27b9a8",
        "settings": "174010f0.fc008f",
        "events": "[{\"start\":{\"dow\":6,\"mod\":180},\"end\":{\"dow\":6,\"mod\":195}},{\"start\":{\"dow\":6,\"mod\":780},\"end\":{\"dow\":6,\"mod\":795}}]",
        "topic": "",
        "name": "FloorHeatingPump Schedule",
        "onPayload": "ON",
        "onPayloadType": "str",
        "offPayload": "OFF",
        "offPayloadType": "str",
        "onlyWhenDark": false,
        "scheduleRndMax": 0,
        "sunElevationThreshold": 6,
        "sunShowElevationInStatus": false,
        "outputfreq": "output.statechange",
        "x": 918.5,
        "y": 580,
        "wires": [
            [
                "c2499e30.a078b",
                "52b4a8a9.7f6aa8"
            ]
        ]
    },
    {
        "id": "50d08bcd.1df4b4",
        "type": "trigger-state",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "server": "40a0d9a7.192b38",
        "entityid": "sensor.seizoen",
        "debugenabled": false,
        "constraints": [],
        "constraintsmustmatch": "all",
        "outputs": 4,
        "customoutputs": [
            {
                "outputId": "wbi2m3ehex",
                "messageType": "default",
                "messageValue": "",
                "comparatorPropertyType": "current_state",
                "comparatorPropertyValue": "new_state.state",
                "comparatorType": "is",
                "comparatorValue": "winter"
            },
            {
                "outputId": "gsheu9rh0dm",
                "messageType": "default",
                "messageValue": "",
                "comparatorPropertyType": "always",
                "comparatorPropertyValue": "",
                "comparatorType": "is",
                "comparatorValue": ""
            }
        ],
        "x": 354.5,
        "y": 597,
        "wires": [
            [],
            [],
            [
                "4d5ddb0d.d8be4c"
            ],
            [
                "7a91184b.bdb4"
            ]
        ]
    },
    {
        "id": "4d5ddb0d.d8be4c",
        "type": "change",
        "z": "81b7e62e.27b9a8",
        "name": "Set state to stop",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "stop",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 616.5,
        "y": 542,
        "wires": [
            [
                "ed62fb74.b88888",
                "1e06ab35.0ba465"
            ]
        ]
    },
    {
        "id": "7a91184b.bdb4",
        "type": "change",
        "z": "81b7e62e.27b9a8",
        "name": "Set state to schedule-only",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "schedule-only",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 645,
        "y": 613,
        "wires": [
            [
                "ed62fb74.b88888",
                "1e06ab35.0ba465"
            ]
        ]
    },
    {
        "id": "c2499e30.a078b",
        "type": "switch",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "ON",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "OFF",
                "vt": "str"
            }
        ],
        "checkall": "false",
        "repair": false,
        "outputs": 2,
        "x": 1158.5,
        "y": 565,
        "wires": [
            [
                "2a0dad43.97342a"
            ],
            [
                "c04e301d.60b9d"
            ]
        ]
    },
    {
        "id": "aca0b190.619238",
        "type": "change",
        "z": "81b7e62e.27b9a8",
        "name": "Set average to get the last 2 minutes of data",
        "rules": [
            {
                "t": "set",
                "p": "startdate",
                "pt": "msg",
                "to": "$fromMillis($toMillis($now())-2000)",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 2030,
        "y": 537,
        "wires": [
            [
                "4443d1bb.7d9778",
                "790883ec.d31cc4"
            ]
        ]
    },
    {
        "id": "4443d1bb.7d9778",
        "type": "api-get-history",
        "z": "81b7e62e.27b9a8",
        "name": "Get average power consumption",
        "server": "40a0d9a7.192b38",
        "startdate": "",
        "enddate": "",
        "entityid": "sensor.toon_p1_power_use_low",
        "entityidtype": "is",
        "x": 2446.7221450805664,
        "y": 482.88886880874634,
        "wires": [
            [
                "de542838.cc22e8",
                "d3ae8d24.218398"
            ]
        ]
    },
    {
        "id": "de542838.cc22e8",
        "type": "function",
        "z": "81b7e62e.27b9a8",
        "name": "Average whilest pump is running",
        "func": "\naverage = 0.0;\ncount = 0;\n\nfor(var object of msg.payload[0]){\n    average += parseFloat(object.state);\n    count++;\n}\n\naverage /= count;\n\nmsg.average = average;\nmsg.count = count;\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 2760,
        "y": 410,
        "wires": [
            [
                "eea3feef.1bf26"
            ]
        ]
    },
    {
        "id": "bd966be4.3200a8",
        "type": "change",
        "z": "81b7e62e.27b9a8",
        "name": "Set average to get 2 seconds of data, starting from 4 seconds ago",
        "rules": [
            {
                "t": "set",
                "p": "enddate",
                "pt": "msg",
                "to": "$fromMillis($toMillis($now())-2000)",
                "tot": "jsonata"
            },
            {
                "t": "set",
                "p": "startdate",
                "pt": "msg",
                "to": "$fromMillis($toMillis($now())-4000)",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 2010,
        "y": 619,
        "wires": [
            [
                "c2e59645.c621b",
                "3b7990.54ddde7"
            ]
        ]
    },
    {
        "id": "c2e59645.c621b",
        "type": "api-get-history",
        "z": "81b7e62e.27b9a8",
        "name": "Get average power consumption",
        "server": "40a0d9a7.192b38",
        "startdate": "",
        "enddate": "",
        "entityid": "sensor.toon_p1_power_use_low",
        "entityidtype": "is",
        "x": 2454.5,
        "y": 550,
        "wires": [
            [
                "f998bfc7.854f7",
                "397d069e.c78aba"
            ]
        ]
    },
    {
        "id": "f998bfc7.854f7",
        "type": "function",
        "z": "81b7e62e.27b9a8",
        "name": "Average whilest pump is running",
        "func": "\naverage = 0.0;\ncount = 0;\n\nfor(var object of msg.payload[0]){\n    average += parseFloat(object.state);\n    count++;\n}\n\naverage /= count;\n\nmsg.average = average;\nmsg.count = count;\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 2780,
        "y": 486,
        "wires": [
            [
                "eea3feef.1bf26"
            ]
        ]
    },
    {
        "id": "a65b003b.e780a",
        "type": "calculator",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "inputMsgField": "average",
        "outputMsgField": "payload",
        "operation": "sub",
        "constant": "",
        "x": 3162.5,
        "y": 531,
        "wires": [
            [
                "7880bcc9.fc6efc",
                "465f0d4.f6b77f4"
            ]
        ]
    },
    {
        "id": "eea3feef.1bf26",
        "type": "join",
        "z": "81b7e62e.27b9a8",
        "name": "Get Averages array",
        "mode": "custom",
        "build": "array",
        "property": "average",
        "propertyType": "msg",
        "key": "topic",
        "joiner": "\\n",
        "joinerType": "str",
        "accumulate": false,
        "timeout": "",
        "count": "2",
        "reduceRight": false,
        "reduceExp": "",
        "reduceInit": "",
        "reduceInitType": "",
        "reduceFixup": "",
        "x": 3060.5,
        "y": 434,
        "wires": [
            [
                "a65b003b.e780a",
                "a6053145.c51688"
            ]
        ]
    },
    {
        "id": "7880bcc9.fc6efc",
        "type": "calculator",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "inputMsgField": "payload",
        "outputMsgField": "payload",
        "operation": "abs",
        "constant": "",
        "x": 3204.5,
        "y": 609,
        "wires": [
            [
                "7b2c2f73.7a1458",
                "b86272ef.d62d68",
                "461bc026.0d2c38"
            ]
        ]
    },
    {
        "id": "60dd5413.598d2c",
        "type": "comment",
        "z": "81b7e62e.27b9a8",
        "name": "Power usage by the pump",
        "info": "The Floor heating pump uses 80W max\nso a threshold of 75W is perfect",
        "x": 3144.4443359375,
        "y": 319.4444580078125,
        "wires": []
    },
    {
        "id": "7b2c2f73.7a1458",
        "type": "function",
        "z": "81b7e62e.27b9a8",
        "name": "Format notification message",
        "func": "\nlowerThreshold = 75.0;\nupperThreshold = 85.0;\n\ntoHigh = false;\ntoLow = false;\n\nif((toHigh = parseFloat(msg.payload) > upperThreshold) | (toLow = parseFloat(msg.payload) < lowerThreshold)){\n    if(toHigh){\n        msg.payload = {\n            \"data\":{\n            \"title\": \"Mogelijk defect apparaat gedetecteerd!\",\n            \"message\": \"Het energie verbruik van de vloerverwarmingspomp was te hoog, tijdens het gebruik. Namelijk \" + msg.payload + \"W.\"\n            }\n        };\n    }else if(toLow){\n        msg.payload = {\n            \"data\":{\n            \"title\": \"Mogelijk defect apparaat gedetecteerd!\",\n            \"message\": \"Het energie verbruik van de vloerverwarmingspomp was te laag, tijdens het gebruik. Namelijk \" + msg.payload + \"W.\"\n            }\n        };\n    }\n}\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 3490.1114196777344,
        "y": 642.22216796875,
        "wires": [
            [
                "9b3680b1.dfbf38"
            ]
        ]
    },
    {
        "id": "9b3680b1.dfbf38",
        "type": "api-call-service",
        "z": "81b7e62e.27b9a8",
        "name": "Notify push notification",
        "server": "40a0d9a7.192b38",
        "service_domain": "notify",
        "service": "technisch",
        "data": "{}",
        "mergecontext": "",
        "x": 3771.77783203125,
        "y": 642.2222900390625,
        "wires": [
            []
        ]
    },
    {
        "id": "c7e2ae85.36dbf8",
        "type": "api-call-service",
        "z": "81b7e62e.27b9a8",
        "name": "Log in HASS logbook",
        "server": "40a0d9a7.192b38",
        "service_domain": "logbook",
        "service": "log",
        "data": "",
        "mergecontext": "",
        "x": 3766.22216796875,
        "y": 741.1111450195312,
        "wires": [
            []
        ]
    },
    {
        "id": "b86272ef.d62d68",
        "type": "function",
        "z": "81b7e62e.27b9a8",
        "name": "Format notification message",
        "func": "\nlowerThreshold = 75.0;\nupperThreshold = 85.0;\n\ntoHigh = false;\ntoLow = false;\n\nif((toHigh = parseFloat(msg.payload) > upperThreshold) | (toLow = parseFloat(msg.payload) < lowerThreshold)){\n    if(toHigh){\n        msg.payload = {\n            \"data\":{\n            \"name\": \"[Node-RED]\",\n            \"message\": \"Het energie verbruik van de vloerverwarmingspomp was te hoog, tijdens het gebruik. Namelijk \" + msg.payload + \"W.\"\n            }\n        };\n    }else if(toLow){\n        msg.payload = {\n            \"data\":{\n            \"name\": \"[Node-RED]\",\n            \"message\": \"Het energie verbruik van de vloerverwarmingspomp was te laag, tijdens het gebruik. Namelijk \" + msg.payload + \"W.\"\n            }\n        };\n    }\n}\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 3482.888916015625,
        "y": 716.666748046875,
        "wires": [
            [
                "c7e2ae85.36dbf8"
            ]
        ]
    },
    {
        "id": "2a0dad43.97342a",
        "type": "api-call-service",
        "z": "81b7e62e.27b9a8",
        "name": "Turn on pump",
        "server": "40a0d9a7.192b38",
        "service_domain": "switch",
        "service": "turn_on",
        "data": "{\"entity_id\":\"switch.floor_heating_pump\"}",
        "mergecontext": "",
        "x": 1412.5,
        "y": 450,
        "wires": [
            []
        ]
    },
    {
        "id": "45a6d8e0.4af038",
        "type": "api-call-service",
        "z": "81b7e62e.27b9a8",
        "name": "Turn off pump",
        "server": "40a0d9a7.192b38",
        "service_domain": "switch",
        "service": "turn_off",
        "data": "{\"entity_id\":\"switch.floor_heating_pump\"}",
        "mergecontext": "",
        "x": 1654,
        "y": 557,
        "wires": [
            [
                "aca0b190.619238",
                "bd966be4.3200a8"
            ]
        ]
    },
    {
        "id": "a6053145.c51688",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 3365.5,
        "y": 420,
        "wires": []
    },
    {
        "id": "465f0d4.f6b77f4",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 3328.5,
        "y": 535,
        "wires": []
    },
    {
        "id": "461bc026.0d2c38",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 3393,
        "y": 587,
        "wires": []
    },
    {
        "id": "d3ae8d24.218398",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 2656,
        "y": 348,
        "wires": []
    },
    {
        "id": "397d069e.c78aba",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 2695,
        "y": 608,
        "wires": []
    },
    {
        "id": "3b7990.54ddde7",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 2323,
        "y": 672,
        "wires": []
    },
    {
        "id": "790883ec.d31cc4",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 2246,
        "y": 441,
        "wires": []
    },
    {
        "id": "52b4a8a9.7f6aa8",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1121,
        "y": 625,
        "wires": []
    },
    {
        "id": "1e06ab35.0ba465",
        "type": "debug",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 843.5,
        "y": 658,
        "wires": []
    },
    {
        "id": "3612f45d.c4983c",
        "type": "inject",
        "z": "81b7e62e.27b9a8",
        "name": "",
        "topic": "schedule-only",
        "payload": "schedule-only",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 791.5,
        "y": 470,
        "wires": [
            [
                "ed62fb74.b88888"
            ]
        ]
    },
    {
        "id": "c04e301d.60b9d",
        "type": "api-current-state",
        "z": "81b7e62e.27b9a8",
        "name": "Is pump currently on?",
        "server": "40a0d9a7.192b38",
        "halt_if": "off",
        "override_topic": true,
        "override_payload": true,
        "entity_id": "switch.floor_heating_pump",
        "x": 1394.7777099609375,
        "y": 572.8888549804688,
        "wires": [
            [
                "45a6d8e0.4af038"
            ]
        ]
    },
    {
        "id": "174010f0.fc008f",
        "type": "light-scheduler-settings",
        "z": "",
        "name": "",
        "latitude": "coordinates",
        "longitude": "coordinates"
    }
]`

**Comment by Ant422** [comment]
Hi,
Did you find a way to resolve this. I am having the same issue even with nothing connected to the input of the node. Every minute it's outputs its state. Yep, I have 'when state changes' selected.
Thanks

**Comment by niklaswall** [comment]
I'm not able to reproduce this behavior. 
If this is still a problem, could someone please provide a flow without external dependencies that reproduces this issue?
