### ISSUE TITLE
Bug when set schedule Sunday until 24.00

### ISSUE THREAD

**Issue by rhoddan** [niklaswall/node-red-contrib-light-scheduler#6]
It's problem to set a scheduler which end sunday 24.00

**Comment by niklaswall** [comment]
Are you using the latest version? I was under the impression that I added a test case for this scenario (since i know it has been a problem).

What is the result? Will it never turn on, or will it not turn off?

**Comment by rhoddan** [comment]
Hej. Misstänker du kan svenska?

Ställer jag in typ bifogad - alla till 24 och deployar - blir det enligt bild.

Vänligen Peter

PS: tack för en grym utveckling!


Skickat från min iPad

**Comment by niklaswall** [comment]
Absolut :-)

Kör du svensk tids-zon på servern?

Jag har nämligen ett unit-test som ska testa exakt detta... men det skulle ju kunna vara fel på testet också. (Issue #5 hintar att det verkar vara något problem med timezones, men jag har inte hunnit kolla varför det inte fungerar som det ska)

/Niklas

**Comment by rhoddan** [comment]
Kör senaste versionen nu men samma fel



Skickat från min iPad

**Comment by rhoddan** [comment]
För att förtydliga - den grafiska baren ändrar sig från att varit inställd till 24.00 söndag till att bli typ 20.30 efter deploy

Skickat från min iPad

**Comment by rhoddan** [comment]
Hmm ser att jag svarat via mail - fick du bilagorna?

**Comment by erikalveflo** [comment]
This is a rendering bug. It should not affect the scheduler, and is therefore missed by the tests. Patch should fix it.

Bra jobbat förresten 👍
