### ISSUE TITLE
Unable to use the timings window in nodered

### ISSUE THREAD

**Issue by tompeel** [niklaswall/node-red-contrib-light-scheduler#62]
Hi, I have the issue where in the light scheduler node its not showing the previously applied times in the weekly schedule.
I also cant add anything to this but i can sort of remove one but another pops up randomly somewhere else?

I'm not quite sure what info you need but I'm running NR1.1.0 on a Raspberry Pi4

**Comment by scottboom** [comment]
I've got the same issue.
The scheduler will sometimes show the first scheduled time-slot when opening. The other scheduled slots appear to be there - you can drag them, but they are invisible.
Currently running NR1.1.3 on Home Assistant running in VM. Was working fine up until a week or two ago - maybe when Node-Red was upgraded to 1.1.0?

**Comment by Bazz-Man** [comment]
Yep I have exactly the same issue, the current schedules still work but you cant see them and if I add a new node and try to config the periods nothing is shown, extremely frustrating!  This is nodered v7.1.0 (which is actually nodered 1.1.3 according the log) on Hassio with docker images

**Comment by scottboom** [comment]
Thanks Bazz-Man -- I just updated as well, and the issue is resolved. Thanks for the tip!

**Comment by EmnaX** [comment]
@Bazz-Man for the win!

I was having the same issues as described above. I'm running the Node-Red add-on V7.1.1 in Home Assistant on a Raspberry Pi 4.

I updated the node through the 'manage palette' option as described and everything is working great again :) I had just assumed that nodes would automatically update themselves. Lesson learned!

**Comment by niklaswall** [comment]
Glad this was solved :-)
