### ISSUE TITLE
Steps in scheduler after 10 minutes

### ISSUE THREAD

**Issue by fatal56ty** [niklaswall/node-red-contrib-light-scheduler#65]
Hi, is possible to set steps after 10 minutes (or 5 minutes) in scheduler not 15 minutes? Im using this scheduler for heating and 15 minutes is much.

**Comment by niklaswall** [comment]
Are you doing some kind of PWM with the scheduler or what? Feels a little bit like the wrong tool for the job, but I don't know your exact needs.

It's definitely possible to change to a "higher resolution", but I'm afraid that it might be trickier to use if the resolution is too high.

I will try it out and see how it behaves when increasing the resolution.

//Niklas

**Comment by XacretT** [comment]
Hi. I'm joining this request
If possible, it would be cool to be able to choose the resolution
In my case i need to do some actions with 1 to 5min intervals. I clearly understand, that this can be done with trigger node, but anyway "resolution picker" will be an awesome feature

I would like to note that I really appreciate the work you have done!

**Comment by fatal56ty** [comment]
I changed value in [https://github.com/niklaswall/node-red-contrib-light-scheduler/search?q=duration](url). Work like a charm.

I changed duration for 5 minuts steps. So I turn on pump every hour for 5 minutes. In web interface is 5 minutes just fine, higher resolution would be a problem.

**Comment by niklaswall** [comment]
Just released version 0.0.17 with five minutes as granularity. I don't think it's possible to make it more granular than this with the current editor.
