### ISSUE TITLE
Wrong time used

### ISSUE THREAD

**Issue by javos65** [niklaswall/node-red-contrib-light-scheduler#68]
Scheduler is using the wrong time.

Always takes UTC, where my location is Netherlands, and we are UTC+1
Location  is set correct and calculated sunset/dawn is also correct.
Local Time is also correct as shown in Node Red debug screen

Only the scheduler wont use the right time

**Comment by niklaswall** [comment]
Are you running node-red in docker?

If so, please read this:
https://github.com/niklaswall/node-red-contrib-light-scheduler/issues/47

//Niklas

**Comment by javos65** [comment]
No, direct install on ras

**Comment by DotOnedotNL** [comment]
I can confirm, I'm in the Netherlands as well and it looks like TZ is not processed correctly.

local time:
$ date
Mon Jan 18 11:54:23 CET 2021

container time:
$ docker exec -it node-red date
Mon Jan 18 10:53:54 UTC 2021

Container environment:
HOSTNAME=automation
TERM=xterm
..
..
PUID=995
PGID=995
TZ="Europe/Amsterdam"
NODE_VERSION=10.23.1
YARN_VERSION=1.22.5
NODE_RED_VERSION=v1.2.7
NODE_PATH=/usr/src/node-red/node_modules:/data/node_modules
FLOWS=flows.json
HOME=/root

//Andre

**Comment by DotOnedotNL** [comment]
Found my issue, the error was completely mine, you can see in the env var TZ, it has quotes around it.
Fixed this and time is correct now.

//Andre
