### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by SergiuToporjinschi** [niklaswall/node-red-contrib-light-scheduler#7]
Hi @niklaswall,
:+1:  I was planning to do exactly this. 
I just created a node red project for controlling my blinds and I was about to plan a project to calculate sun position to trigger the RF command to rise blinds (https://github.com/SergiuToporjinschi/rf-command) :) 
You did a greate job here, I will give it a try. Nice work. Looks goof for now. 
I thing you can remove the word "light" from the title, because you can schedule anything there.
Keep it going!

**Comment by SergiuToporjinschi** [comment]
To give you the first feedback: 
I don't know if this is an issue or I'm not familiar to it: 

- I think would be nice to have another option on output something like "on input" end send the payload when you have something(on or off) in input. 

- Naming on and off is a little confusing for my scenario, for me would be nice if I can name those; 

- Another thing which seems confusing is that calendar because I don't know what i'm selecting, On state or off state? a legend will be nice there or some description in info tab;

**Comment by niklaswall** [comment]
Hi,

I agree that the naming is a little bit off now, the project has grown from my original idea, so it's now much more competent.

If you have a better idea than on / off I'm an eager listener. I wanted something as neutral as possible and is relatively easy to associate with the marked schedule (selection == on) I did not manage to come up with a better name at the moment. Any ideas are very much welcomed!

**Comment by niklaswall** [comment]
I have made some clarifications on the schedule so that it's clear that a marked schedule is equal to "ON".

In some scenarios, it would make sense to "rename properties" (like ON/OFF) in node-red, but I think it's actually not that often it's needed, so it's a corner case.
