### ISSUE TITLE
Randomize timer

### ISSUE THREAD

**Issue by dionmes** [niklaswall/node-red-contrib-light-scheduler#9]
Really want to use this timer, it has some features I really would like to use like minutely and the 'auto' input. But for me preventing to use it, is the absence of a randomise feature. So the on and off times can be triggered with a random delay for example between 0 and 30 minutes. Besides that, the best looking timer.

**Comment by niklaswall** [comment]
Interesting idea... is it enough to have this up to 15 minutes?

**Comment by dionmes** [comment]
Well, it would be enough although 30-1 hour would be preferable to simulate someones presence which I would use It for. But 15 minutes would be enough for me to start using it.

**Comment by niklaswall** [comment]
Ok, I will look into this when I have some time over :-)

**Comment by niklaswall** [comment]
I have now added randomization to the schedule (not published to NPM yet).
The schedule can be randomized with up to +/- 60 minutes. I hope this solves your need! :-)

**Comment by dionmes** [comment]
Awesome! Thx m8. Thats really quick, gonna implement this asap.

**Comment by dionmes** [comment]
Hi,

Everything allright? 

I was wondering should I install your node update with randomisation from the GitHub or can I wait for the NPM release? 
Maybe I am just lazy but I like to update from the node-red ‘manage palette’ manager.

Kind regards,
Dion
